name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        minecraft: [ 1.20.4 ]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Setup files
        run: ./gradlew forge:setupFiles -Pminecraft_version="${{ matrix.minecraft }}"

      - name: Build with Gradle Wrapper
        run: |
          NOW=$(date '+%Y-%m-%d-%H.%M')
          ./gradlew build -Pminecraft_version="${{ matrix.minecraft }}" -Partifact_date=".artifact_$NOW" --scan
